const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const {test} = require('node:test');
const app = fs.readFileSync(__dirname + '/../assets/app.js', 'utf8');
const server = fs.readFileSync(process.env.BUNMYAKU_TEST_SERVER || __dirname + '/../apps-script/Code.gs', 'utf8');
const base = Date.parse('2026-10-01T00:00:00Z');
const question = {questionId:'fixture',releaseDate:'2026-10-01',title:'fixture',paragraphs:[],correctOrder:['A','B','C','D','E','F'],feedbackRules:[]};
function client() {
  let wall=base, mono=0, actions=[], handler=async action=>action==='status'?{today:'2026-10-01',available:true}: {result:{correct:true,answer:[],correctOrder:[]}};
  const storage=new Map(), root={innerHTML:''}, el={addEventListener(){},textContent:''};
  const c={console,Date:class extends Date {constructor(...a){super(...(a.length?a:[wall]));} static now(){return wall;}},performance:{now:()=>mono},document:{getElementById:id=>id==='app'?root:el,querySelector:()=>el,querySelectorAll:()=>[]},window:{BUNMYAKU_CONFIG:{apiUrl:'https://fixture.invalid'},setTimeout:cb=>{queueMicrotask(cb);return 1;},clearTimeout(){},setInterval:()=>1,clearInterval(){},scrollTo(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:async(url,opt)=>{const body=opt.method==='POST'?JSON.parse(opt.body):{action:'status'};actions.push(body);return {ok:true,json:async()=>({ok:true,data:await handler(body.action,body)})};}};
  vm.createContext(c);vm.runInContext(app.replace('  bootstrap();','  globalThis.audit={state,setClock,phaseInfo,beginAttempt,bootstrap,submitAttempt,isSubmitting:()=>submitting};'),c);
  c.audit.state.attempt={attemptId:'fixture',attemptToken:'synthetic',timerVersion:2,practiceDate:'2026-10-01',startedAt:new Date(base).toISOString(),question,timing:{readingSeconds:120,answerSeconds:60,totalSeconds:180}};
  c.audit.setClock(0);
  return {c,actions,storage,root,advance:s=>{mono+=s*1000;wall+=s*1000;},skew:s=>wall+=s*1000,handle:f=>handler=f};
}
function backend() {
  let now=base, saved=[], failAppend=false, failFinalize=false;
  const active={attemptId:'fixture',attemptToken:'synthetic',studentId:'fixture',questionId:'fixture',practiceDate:'2026-10-01',startedAt:new Date(base).toISOString(),status:'started',timerVersion:2,rowNumber:2,resultJson:''};
  const c={console,Date:class extends Date {constructor(...a){super(...(a.length?a:[now]));} static now(){return now;}}};vm.createContext(c);vm.runInContext(server,c);
  Object.assign(c,{LockService:{getDocumentLock:()=>({waitLock(){},releaseLock(){}})},getActiveAttemptById_:()=>active,getConfig_:()=>({TOTAL_SECONDS:180,READING_SECONDS:120,ANSWER_SECONDS:60}),getQuestionById_:()=>question,getStudent_:()=>({active:true,fullName:'fixture',campus:'fixture'}),tokyoDate_:()=> '2026-10-01',getSubmittedRows_:()=>saved,requiredSheet_:()=>({getRange:(_row,col)=>({setNumberFormat(){},setValues:values=>{if(col===6){active.startedAt=values[0][0].toISOString();active.status=values[0][1];}else {if(failFinalize&&values[0][0]==='submitted')throw Error('finalize failed');active.status=values[0][0];active.resultJson=values[0][1];}}})}),appendSubmittedAttempt_:(_a,_s,_q,result)=>{if(failAppend)throw Error('append failed');saved.push({attemptId:active.attemptId,...result});}});
  const body=()=>({attemptId:'fixture',attemptToken:'synthetic',answer:['A','B','C','D','E','F'],elapsedSeconds:150});
  return {c,active,body,saved,at:s=>now=base+s*1000,failAppend:v=>failAppend=v,failFinalize:v=>failFinalize=v};
}
test('clock skew and clock changes never advance or rewind the running timer',()=>{const t=client();t.skew(180);assert.equal(t.c.audit.phaseInfo().remaining,120);t.advance(30);t.skew(-7200);assert.equal(t.c.audit.phaseInfo().remaining,90);t.advance(90);assert.equal(t.c.audit.phaseInfo().phase,'answer');t.advance(60);assert.equal(t.c.audit.phaseInfo().phase,'locked');});
test('delayed question download does not consume reading time',async()=>{const t=client();const attempt=t.c.audit.state.attempt;attempt.startedAt='';t.handle(async action=>{if(action==='startAttempt'){t.advance(30);return attempt;}return {startedAt:new Date(base+30000).toISOString()};});await t.c.audit.beginAttempt();assert.equal(t.c.audit.phaseInfo().remaining,120);assert.ok(t.actions.some(x=>x.action==='activateAttempt'));});
test('storage denied does not block grading, result rendering or reset submitting',async()=>{const t=client();for(const k of ['getItem','setItem','removeItem'])t.c.localStorage[k]=()=>{throw Error('blocked storage');};t.advance(150);await t.c.audit.submitAttempt();assert.ok(t.actions.some(x=>x.action==='submitAttempt'));assert.equal(t.c.audit.isSubmitting(),false);assert.match(t.root.innerHTML,/正解/);});
test('storage denied on bootstrap still renders the entry',async()=>{const t=client();t.c.localStorage.getItem=()=>{throw Error('blocked storage');};await t.c.audit.bootstrap();assert.match(t.root.innerHTML,/student-form/);});
test('retry retains original answer and elapsed time even without storage',async()=>{const t=client();let fail=true, sent=[];t.c.localStorage.setItem=()=>{throw Error('quota');};t.handle(async(action,b)=>{if(action==='submitAttempt'){sent.push(b);if(fail)throw Error('offline');}return {result:{correct:true,answer:[],correctOrder:[]}};});t.advance(150);t.c.audit.state.answer=['A'];await t.c.audit.submitAttempt();assert.equal(sent.length,5);assert.equal(t.c.audit.isSubmitting(),false);fail=false;t.advance(100);t.c.audit.state.answer=['B'];await t.c.audit.submitAttempt();assert.deepEqual(sent[5].answer,['A']);assert.equal(sent[5].elapsedSeconds,150);});
test('stale draft is not resumed or automatically submitted',async()=>{const t=client();t.c.audit.state.attempt.practiceDate='2026-09-30';t.storage.set('bunmyaku-shobu-active-attempt-v6',JSON.stringify({attempt:t.c.audit.state.attempt}));await t.c.audit.bootstrap();assert.deepEqual(t.actions.map(x=>x.action),['status']);assert.match(t.root.innerHTML,/student-form/);});
test('reload obtains elapsed time from server, not device clock',async()=>{const t=client();t.storage.set('bunmyaku-shobu-active-attempt-v6',JSON.stringify({attempt:t.c.audit.state.attempt,answer:[]}));t.skew(3600);t.handle(async action=>action==='status'?{available:true,today:'2026-10-01'}:{...t.c.audit.state.attempt,elapsedSeconds:75});await t.c.audit.bootstrap();assert.equal(t.c.audit.phaseInfo().remaining,45);});
test('activation is idempotent and never resets a started attempt',()=>{const t=backend();t.active.status='prepared';t.active.startedAt='';t.at(30);t.c.activateAttempt_({...t.body(),elapsedSeconds:0});const start=t.active.startedAt;t.at(80);t.c.activateAttempt_({...t.body(),elapsedSeconds:0});assert.equal(t.active.startedAt,start);});
test('saved append plus failed finalization does not append again',()=>{const t=backend();t.at(150);t.failFinalize(true);assert.throws(()=>t.c.submitAttempt_(t.body()),/finalize/);assert.equal(t.saved.length,1);t.failFinalize(false);const r=t.c.submitAttempt_(t.body());assert.equal(r.result.correct,true);assert.equal(r.duplicate,true);assert.equal(t.saved.length,1);});
test('failed append preserves original grading on retry with changed answer',()=>{const t=backend();t.at(150);t.failAppend(true);assert.throws(()=>t.c.submitAttempt_(t.body()),/append/);t.failAppend(false);t.at(250);const result=t.c.submitAttempt_({...t.body(),answer:['B','A','C','D','E','F'],elapsedSeconds:220});assert.equal(result.result.correct,true);assert.equal(result.result.elapsedSeconds,150);assert.equal(t.saved.length,1);});
test('late network delivery preserves timely submission; actual deadline remains enforced',()=>{const t=backend();t.at(400);assert.equal(t.c.submitAttempt_(t.body()).result.correct,true);const u=backend();u.at(200);assert.equal(u.c.submitAttempt_({...u.body(),elapsedSeconds:180}).result.timedOut,true);});
test('invalid token, early answer and invalid elapsed time do not write results',()=>{const t=backend();t.at(150);assert.throws(()=>t.c.submitAttempt_({...t.body(),attemptToken:'wrong'}));assert.throws(()=>t.c.submitAttempt_({...t.body(),elapsedSeconds:-1}));assert.throws(()=>t.c.submitAttempt_({...t.body(),elapsedSeconds:90000}));assert.throws(()=>t.c.submitAttempt_({...t.body(),elapsedSeconds:10}));assert.equal(t.saved.length,0);});
test('activation queued for 30 seconds does not reject a timely answer',()=>{const t=backend();t.active.status='prepared';t.active.startedAt='';t.at(30);t.c.activateAttempt_({...t.body(),elapsedSeconds:0});t.at(150);assert.equal(t.c.submitAttempt_(t.body()).result.correct,true);});


